version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 7.3.0
  - dependency-name: coverage
    versions:
    - "7.13.4"
  - dependency-name: pytest
    versions:
    - 9.0.2
  - dependency-name: isort
    versions:
    - 8.0.1
  - dependency-name: django-debug-toolbar
    versions:
    - "6.2.0"
  - dependency-name: pytest-django
    versions:
    - 4.12.0
