[tox]
envlist =
    python{3.13,3.14}-django{5.2}-wagtail{7.0}

[gh-actions]
python =
    3.13: python3.13
    3.14: python3.14

[testenv]
commands = coverage run --parallel -m pytest {posargs} -vvv

basepython =
    python3.13: python3.13
    python3.14: python3.14

deps =
    django5.2: Django>=5.2,<6.0
    wagtail7.0: wagtail>=7.0,<7.1

extras = test

[testenv:coverage-report]
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report
